import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry"; // Import the registry
import ConditionalHeader from "@/app/Component/header/ConditionalHeader";
import SimulationBanner from "@/app/Component/SimulationBanner";
import "./material-symbols.css";
import { getUser } from "./actions/auth";

import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StyledComponentsRegistry>
          <SimulationBanner />
          <ConditionalHeader user={user} />
          {children}
          <Toaster />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
